databases:
  - name: Totonoi_DB
    databaseName: Totonoi_db
    user: Totonoi
    region: singapore

services:
  - type: web
    name: Totonoi
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Totonoi_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

